/********************************************************************************
** Form generated from reading UI file 'control_interface.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONTROL_INTERFACE_H
#define UI_CONTROL_INTERFACE_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "control_interface.h"

QT_BEGIN_NAMESPACE

class Ui_control_interface
{
public:
    Label_awb *label_awb;
    Label_freeze *label_freeze;
    Label_photograph *label_photograph;
    Label_videoint *label_video;
    Label_ae *label_ae;
    Label_led *label_led;
    Label_interface *label_interface;
    QLabel *label_versions;
    QLabel *label_times;
    QLabel *label_month_day;
    QLabel *label_years;
    QLabel *labelw_awb;
    QLabel *labelw_zoom;
    QLabel *label_atom;
    QLabel *label_zoomnum;
    QLabel *labelw_picture;
    Label_picture_mode *label_picture_mode;
    QLabel *labelw_show;
    Label_display_mode *label_display_mode;
    QLabel *labelw_language;
    QLabel *label_language_c;
    QLabel *labelw_time;
    QLabel *label_timenum;
    QLabel *labelw_number;
    QLabel *label_use_num;
    QLabel *label_b;
    Label_custom1 *label_custom1;
    Label_custom2 *label_custom2;
    Label_custom3 *label_custom3;
    Label_pump *label_pump;
    Label_rotate *label_rotate;
    Label_store *label_store;
    Label_frames *label_frames;
    QLabel *label_time;
    Label_screen_left *label_screen_left;
    Label_screen_right *label_screen_right;
    QLabel *label_status;
    QLabel *label_mtoa;
    QLabel *label_picture_1;
    QLabel *label_picture_2;
    QLabel *label_picture_3;
    QLabel *label_picture_4;
    QLabel *label_picture_5;
    QLabel *label_language_ct;
    QLabel *label_language_e;
    Label_display_mode *label_display_1;
    Label_display_mode *label_display_2;
    Label_display_mode *label_display_3;
    QLabel *label_versions_num;
    Label_host_led *label_host_led;
    QLabel *label_1;
    QLabel *label_2;
    QLabel *label_3;
    QPushButton *browseReportBtn;
    QLabel *label_curPatient;
    QPushButton *zoomBtn;
    QLabel *battery;

    void setupUi(QWidget *control_interface)
    {
        if (control_interface->objectName().isEmpty())
            control_interface->setObjectName(QString::fromUtf8("control_interface"));
        control_interface->resize(1280, 800);
        control_interface->setStyleSheet(QString::fromUtf8(""));
        label_awb = new Label_awb(control_interface);
        label_awb->setObjectName(QString::fromUtf8("label_awb"));
        label_awb->setGeometry(QRect(1120, 0, 160, 80));
        label_awb->setStyleSheet(QString::fromUtf8("background-image: url(:/tu/AWB.png);"));
        label_freeze = new Label_freeze(control_interface);
        label_freeze->setObjectName(QString::fromUtf8("label_freeze"));
        label_freeze->setGeometry(QRect(1120, 80, 160, 80));
        label_freeze->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/Freeze/freeze.png);"));
        label_photograph = new Label_photograph(control_interface);
        label_photograph->setObjectName(QString::fromUtf8("label_photograph"));
        label_photograph->setGeometry(QRect(1120, 240, 160, 80));
        label_photograph->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/takephoto.png);"));
        label_video = new Label_videoint(control_interface);
        label_video->setObjectName(QString::fromUtf8("label_video"));
        label_video->setGeometry(QRect(1120, 320, 160, 80));
        label_video->setStyleSheet(QString::fromUtf8("background-image: url(:/tu/rec.png);"));
        label_ae = new Label_ae(control_interface);
        label_ae->setObjectName(QString::fromUtf8("label_ae"));
        label_ae->setGeometry(QRect(1120, 400, 160, 80));
        label_ae->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/AE/AE1.png);"));
        label_led = new Label_led(control_interface);
        label_led->setObjectName(QString::fromUtf8("label_led"));
        label_led->setGeometry(QRect(1120, 560, 160, 80));
        label_led->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/LED/LED1.png);"));
        label_interface = new Label_interface(control_interface);
        label_interface->setObjectName(QString::fromUtf8("label_interface"));
        label_interface->setGeometry(QRect(1120, 720, 160, 80));
        label_interface->setStyleSheet(QString::fromUtf8("background-image: url(:/tu/maininterface.png);"));
        label_versions = new QLabel(control_interface);
        label_versions->setObjectName(QString::fromUtf8("label_versions"));
        label_versions->setGeometry(QRect(10, 750, 70, 40));
        label_versions->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_versions->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_times = new QLabel(control_interface);
        label_times->setObjectName(QString::fromUtf8("label_times"));
        label_times->setGeometry(QRect(10, 720, 80, 19));
        label_times->setStyleSheet(QString::fromUtf8(""));
        label_month_day = new QLabel(control_interface);
        label_month_day->setObjectName(QString::fromUtf8("label_month_day"));
        label_month_day->setGeometry(QRect(10, 680, 90, 30));
        label_month_day->setStyleSheet(QString::fromUtf8(""));
        label_years = new QLabel(control_interface);
        label_years->setObjectName(QString::fromUtf8("label_years"));
        label_years->setGeometry(QRect(10, 640, 78, 30));
        label_years->setStyleSheet(QString::fromUtf8(""));
        labelw_awb = new QLabel(control_interface);
        labelw_awb->setObjectName(QString::fromUtf8("labelw_awb"));
        labelw_awb->setGeometry(QRect(10, 70, 70, 40));
        labelw_awb->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_awb->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelw_zoom = new QLabel(control_interface);
        labelw_zoom->setObjectName(QString::fromUtf8("labelw_zoom"));
        labelw_zoom->setGeometry(QRect(10, 140, 70, 20));
        labelw_zoom->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_zoom->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_atom = new QLabel(control_interface);
        label_atom->setObjectName(QString::fromUtf8("label_atom"));
        label_atom->setGeometry(QRect(90, 80, 50, 20));
        label_atom->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_zoomnum = new QLabel(control_interface);
        label_zoomnum->setObjectName(QString::fromUtf8("label_zoomnum"));
        label_zoomnum->setGeometry(QRect(88, 135, 25, 30));
        label_zoomnum->setStyleSheet(QString::fromUtf8(""));
        labelw_picture = new QLabel(control_interface);
        labelw_picture->setObjectName(QString::fromUtf8("labelw_picture"));
        labelw_picture->setGeometry(QRect(10, 180, 70, 40));
        labelw_picture->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_picture->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_picture_mode = new Label_picture_mode(control_interface);
        label_picture_mode->setObjectName(QString::fromUtf8("label_picture_mode"));
        label_picture_mode->setGeometry(QRect(88, 185, 65, 30));
        label_picture_mode->setStyleSheet(QString::fromUtf8(""));
        labelw_show = new QLabel(control_interface);
        labelw_show->setObjectName(QString::fromUtf8("labelw_show"));
        labelw_show->setGeometry(QRect(0, 240, 80, 40));
        labelw_show->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_show->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_display_mode = new Label_display_mode(control_interface);
        label_display_mode->setObjectName(QString::fromUtf8("label_display_mode"));
        label_display_mode->setGeometry(QRect(88, 245, 70, 30));
        label_display_mode->setStyleSheet(QString::fromUtf8(""));
        labelw_language = new QLabel(control_interface);
        labelw_language->setObjectName(QString::fromUtf8("labelw_language"));
        labelw_language->setGeometry(QRect(0, 298, 80, 20));
        labelw_language->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_language->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_language_c = new QLabel(control_interface);
        label_language_c->setObjectName(QString::fromUtf8("label_language_c"));
        label_language_c->setGeometry(QRect(90, 300, 65, 20));
        label_language_c->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_time = new QLabel(control_interface);
        labelw_time->setObjectName(QString::fromUtf8("labelw_time"));
        labelw_time->setGeometry(QRect(10, 400, 70, 40));
        labelw_time->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_time->setAlignment(Qt::AlignCenter);
        label_timenum = new QLabel(control_interface);
        label_timenum->setObjectName(QString::fromUtf8("label_timenum"));
        label_timenum->setGeometry(QRect(10, 440, 140, 30));
        label_timenum->setLayoutDirection(Qt::RightToLeft);
        label_timenum->setStyleSheet(QString::fromUtf8(""));
        labelw_number = new QLabel(control_interface);
        labelw_number->setObjectName(QString::fromUtf8("labelw_number"));
        labelw_number->setGeometry(QRect(10, 470, 70, 40));
        labelw_number->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        labelw_number->setAlignment(Qt::AlignCenter);
        label_use_num = new QLabel(control_interface);
        label_use_num->setObjectName(QString::fromUtf8("label_use_num"));
        label_use_num->setGeometry(QRect(88, 480, 70, 30));
        label_use_num->setLayoutDirection(Qt::RightToLeft);
        label_use_num->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_b = new QLabel(control_interface);
        label_b->setObjectName(QString::fromUtf8("label_b"));
        label_b->setGeometry(QRect(0, 0, 1280, 800));
        label_b->setStyleSheet(QString::fromUtf8("background-image: url(:/tu/square.png);"));
        label_b->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_custom1 = new Label_custom1(control_interface);
        label_custom1->setObjectName(QString::fromUtf8("label_custom1"));
        label_custom1->setGeometry(QRect(120, 530, 50, 70));
        label_custom1->setStyleSheet(QString::fromUtf8("image: url(:/tu/\346\227\240\345\212\237\350\203\275.png);"));
        label_custom2 = new Label_custom2(control_interface);
        label_custom2->setObjectName(QString::fromUtf8("label_custom2"));
        label_custom2->setGeometry(QRect(60, 530, 50, 70));
        label_custom2->setStyleSheet(QString::fromUtf8("image: url(:/tu/\346\227\240\345\212\237\350\203\275.png);"));
        label_custom3 = new Label_custom3(control_interface);
        label_custom3->setObjectName(QString::fromUtf8("label_custom3"));
        label_custom3->setGeometry(QRect(0, 530, 50, 70));
        label_custom3->setStyleSheet(QString::fromUtf8("image: url(:/tu/\346\227\240\345\212\237\350\203\275.png);"));
        label_pump = new Label_pump(control_interface);
        label_pump->setObjectName(QString::fromUtf8("label_pump"));
        label_pump->setGeometry(QRect(1120, 640, 160, 80));
        label_pump->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/Pump/pump0.png);"));
        label_rotate = new Label_rotate(control_interface);
        label_rotate->setObjectName(QString::fromUtf8("label_rotate"));
        label_rotate->setGeometry(QRect(1120, 160, 160, 80));
        label_rotate->setStyleSheet(QString::fromUtf8("border-image: url(:/tu/Rotate/rotate0.png);"));
        label_store = new Label_store(control_interface);
        label_store->setObjectName(QString::fromUtf8("label_store"));
        label_store->setGeometry(QRect(880, 30, 160, 87));
        label_store->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_store->setAlignment(Qt::AlignCenter);
        label_frames = new Label_frames(control_interface);
        label_frames->setObjectName(QString::fromUtf8("label_frames"));
        label_frames->setGeometry(QRect(190, 500, 280, 280));
        label_frames->setStyleSheet(QString::fromUtf8(""));
        label_time = new QLabel(control_interface);
        label_time->setObjectName(QString::fromUtf8("label_time"));
        label_time->setGeometry(QRect(570, 5, 140, 30));
        label_screen_left = new Label_screen_left(control_interface);
        label_screen_left->setObjectName(QString::fromUtf8("label_screen_left"));
        label_screen_left->setGeometry(QRect(185, 30, 425, 395));
        label_screen_left->setStyleSheet(QString::fromUtf8(""));
        label_screen_right = new Label_screen_right(control_interface);
        label_screen_right->setObjectName(QString::fromUtf8("label_screen_right"));
        label_screen_right->setGeometry(QRect(660, 30, 425, 395));
        label_screen_right->setStyleSheet(QString::fromUtf8(""));
        label_status = new QLabel(control_interface);
        label_status->setObjectName(QString::fromUtf8("label_status"));
        label_status->setGeometry(QRect(0, 20, 175, 30));
        label_status->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_status->setAlignment(Qt::AlignCenter);
        label_mtoa = new QLabel(control_interface);
        label_mtoa->setObjectName(QString::fromUtf8("label_mtoa"));
        label_mtoa->setGeometry(QRect(90, 80, 50, 20));
        label_mtoa->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_picture_1 = new QLabel(control_interface);
        label_picture_1->setObjectName(QString::fromUtf8("label_picture_1"));
        label_picture_1->setGeometry(QRect(90, 190, 65, 20));
        label_picture_1->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_picture_2 = new QLabel(control_interface);
        label_picture_2->setObjectName(QString::fromUtf8("label_picture_2"));
        label_picture_2->setGeometry(QRect(90, 190, 65, 20));
        label_picture_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_picture_3 = new QLabel(control_interface);
        label_picture_3->setObjectName(QString::fromUtf8("label_picture_3"));
        label_picture_3->setGeometry(QRect(90, 190, 65, 20));
        label_picture_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_picture_4 = new QLabel(control_interface);
        label_picture_4->setObjectName(QString::fromUtf8("label_picture_4"));
        label_picture_4->setGeometry(QRect(90, 190, 65, 20));
        label_picture_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_picture_5 = new QLabel(control_interface);
        label_picture_5->setObjectName(QString::fromUtf8("label_picture_5"));
        label_picture_5->setGeometry(QRect(90, 190, 65, 20));
        label_picture_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_language_ct = new QLabel(control_interface);
        label_language_ct->setObjectName(QString::fromUtf8("label_language_ct"));
        label_language_ct->setGeometry(QRect(90, 300, 65, 20));
        label_language_ct->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_language_e = new QLabel(control_interface);
        label_language_e->setObjectName(QString::fromUtf8("label_language_e"));
        label_language_e->setGeometry(QRect(90, 300, 70, 20));
        label_language_e->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_display_1 = new Label_display_mode(control_interface);
        label_display_1->setObjectName(QString::fromUtf8("label_display_1"));
        label_display_1->setGeometry(QRect(90, 250, 70, 20));
        label_display_1->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_display_2 = new Label_display_mode(control_interface);
        label_display_2->setObjectName(QString::fromUtf8("label_display_2"));
        label_display_2->setGeometry(QRect(90, 250, 70, 20));
        label_display_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_display_3 = new Label_display_mode(control_interface);
        label_display_3->setObjectName(QString::fromUtf8("label_display_3"));
        label_display_3->setGeometry(QRect(90, 250, 70, 20));
        label_display_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_versions_num = new QLabel(control_interface);
        label_versions_num->setObjectName(QString::fromUtf8("label_versions_num"));
        label_versions_num->setGeometry(QRect(90, 762, 90, 20));
        label_versions_num->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_host_led = new Label_host_led(control_interface);
        label_host_led->setObjectName(QString::fromUtf8("label_host_led"));
        label_host_led->setEnabled(false);
        label_host_led->setGeometry(QRect(1070, 770, 41, 21));
        label_host_led->setStyleSheet(QString::fromUtf8("background-image: url(:/tu/LED/hostled2.png);"));
        label_1 = new QLabel(control_interface);
        label_1->setObjectName(QString::fromUtf8("label_1"));
        label_1->setGeometry(QRect(10, 510, 30, 30));
        label_1->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_1->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(control_interface);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(70, 510, 30, 30));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(control_interface);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(130, 510, 30, 30));
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_3->setAlignment(Qt::AlignCenter);
        browseReportBtn = new QPushButton(control_interface);
        browseReportBtn->setObjectName(QString::fromUtf8("browseReportBtn"));
        browseReportBtn->setGeometry(QRect(1120, 480, 160, 80));
        browseReportBtn->setFocusPolicy(Qt::NoFocus);
        browseReportBtn->setStyleSheet(QString::fromUtf8("border:5px solid white;"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/tu/ALL-IN-ONE ICON/icon_browseReport.png"), QSize(), QIcon::Normal, QIcon::Off);
        browseReportBtn->setIcon(icon);
        browseReportBtn->setIconSize(QSize(80, 80));
        browseReportBtn->setFlat(true);
        label_curPatient = new QLabel(control_interface);
        label_curPatient->setObjectName(QString::fromUtf8("label_curPatient"));
        label_curPatient->setGeometry(QRect(0, 330, 171, 81));
        QFont font;
        font.setPointSize(15);
        label_curPatient->setFont(font);
        label_curPatient->setText(QString::fromUtf8("default"));
        label_curPatient->setAlignment(Qt::AlignCenter);
        zoomBtn = new QPushButton(control_interface);
        zoomBtn->setObjectName(QString::fromUtf8("zoomBtn"));
        zoomBtn->setGeometry(QRect(113, 135, 45, 30));
        zoomBtn->setStyleSheet(QString::fromUtf8("border:none;\n"
"image: url(:/tu/Video/advance.png);"));
        battery = new QLabel(control_interface);
        battery->setObjectName(QString::fromUtf8("battery"));
        battery->setGeometry(QRect(150, 10, 61, 31));
        battery->setPixmap(QPixmap(QString::fromUtf8(":/tu/battery_icon/battery4.png")));
        battery->setScaledContents(true);
        battery->setAlignment(Qt::AlignCenter);
        label_b->raise();
        label_awb->raise();
        label_freeze->raise();
        label_photograph->raise();
        label_video->raise();
        label_ae->raise();
        label_led->raise();
        label_interface->raise();
        label_versions->raise();
        label_times->raise();
        label_month_day->raise();
        label_years->raise();
        labelw_awb->raise();
        labelw_zoom->raise();
        label_atom->raise();
        label_zoomnum->raise();
        labelw_picture->raise();
        labelw_show->raise();
        labelw_language->raise();
        label_language_c->raise();
        labelw_time->raise();
        label_timenum->raise();
        labelw_number->raise();
        label_use_num->raise();
        label_custom1->raise();
        label_custom2->raise();
        label_custom3->raise();
        label_pump->raise();
        label_rotate->raise();
        label_store->raise();
        label_frames->raise();
        label_time->raise();
        label_screen_right->raise();
        label_status->raise();
        label_mtoa->raise();
        label_picture_1->raise();
        label_picture_2->raise();
        label_picture_3->raise();
        label_picture_4->raise();
        label_picture_5->raise();
        label_picture_mode->raise();
        label_language_ct->raise();
        label_language_e->raise();
        label_display_1->raise();
        label_display_2->raise();
        label_display_3->raise();
        label_display_mode->raise();
        label_versions_num->raise();
        label_host_led->raise();
        label_1->raise();
        label_2->raise();
        label_3->raise();
        browseReportBtn->raise();
        label_curPatient->raise();
        zoomBtn->raise();
        label_screen_left->raise();
        battery->raise();

        retranslateUi(control_interface);

        QMetaObject::connectSlotsByName(control_interface);
    } // setupUi

    void retranslateUi(QWidget *control_interface)
    {
        control_interface->setWindowTitle(QApplication::translate("control_interface", "Form", nullptr));
        label_awb->setText(QString());
        label_freeze->setText(QString());
        label_photograph->setText(QString());
        label_video->setText(QString());
        label_ae->setText(QString());
        label_led->setText(QString());
        label_interface->setText(QString());
        label_versions->setText(QApplication::translate("control_interface", "\345\275\223\345\211\215\347\211\210\346\234\254:", nullptr));
        label_times->setText(QApplication::translate("control_interface", "16:26:00", nullptr));
        label_month_day->setText(QApplication::translate("control_interface", "05/21", nullptr));
        label_years->setText(QApplication::translate("control_interface", "2025", nullptr));
        labelw_awb->setText(QApplication::translate("control_interface", "\347\231\275\345\271\263\350\241\241:", nullptr));
        labelw_zoom->setText(QApplication::translate("control_interface", "\347\274\251\346\224\276\345\200\215\346\225\260:", nullptr));
        label_atom->setText(QApplication::translate("control_interface", "\346\211\213\345\212\250", nullptr));
        label_zoomnum->setText(QApplication::translate("control_interface", "x4", nullptr));
        labelw_picture->setText(QApplication::translate("control_interface", "\347\224\273\351\235\242\346\250\241\345\274\217:", nullptr));
        label_picture_mode->setText(QString());
        labelw_show->setText(QApplication::translate("control_interface", "\346\230\276\347\244\272\346\250\241\345\274\217:", nullptr));
        label_display_mode->setText(QString());
        labelw_language->setText(QApplication::translate("control_interface", "\350\257\255\350\250\200:", nullptr));
        label_language_c->setText(QApplication::translate("control_interface", "\347\256\200\344\275\223\344\270\255\346\226\207", nullptr));
        labelw_time->setText(QApplication::translate("control_interface", "\344\275\277\347\224\250\346\227\266\351\225\277:", nullptr));
        label_timenum->setText(QString());
        labelw_number->setText(QApplication::translate("control_interface", "\344\275\277\347\224\250\346\254\241\346\225\260:", nullptr));
        label_use_num->setText(QApplication::translate("control_interface", "1", nullptr));
        label_b->setText(QString());
        label_custom1->setText(QString());
        label_custom2->setText(QString());
        label_custom3->setText(QString());
        label_pump->setText(QString());
        label_rotate->setText(QString());
        label_store->setText(QApplication::translate("control_interface", "\345\202\250\345\255\230", nullptr));
        label_frames->setText(QString());
        label_time->setText(QApplication::translate("control_interface", "0:00", nullptr));
        label_screen_left->setText(QString());
        label_screen_right->setText(QString());
        label_status->setText(QApplication::translate("control_interface", "\347\212\266\346\200\201\344\277\241\346\201\257", nullptr));
        label_mtoa->setText(QApplication::translate("control_interface", "\350\207\252\345\212\250", nullptr));
        label_picture_1->setText(QApplication::translate("control_interface", "\345\210\235\345\247\213", nullptr));
        label_picture_2->setText(QApplication::translate("control_interface", "\345\234\206\345\275\242", nullptr));
        label_picture_3->setText(QApplication::translate("control_interface", "\345\205\253\350\247\222\345\275\242", nullptr));
        label_picture_4->setText(QApplication::translate("control_interface", "\346\244\255\345\234\206", nullptr));
        label_picture_5->setText(QApplication::translate("control_interface", "\347\237\251\345\275\242", nullptr));
        label_language_ct->setText(QApplication::translate("control_interface", "\347\271\201\344\275\223\344\270\255\346\226\207", nullptr));
        label_language_e->setText(QApplication::translate("control_interface", "\350\213\261\346\226\207", nullptr));
        label_display_1->setText(QApplication::translate("control_interface", "\345\215\225\347\224\273\351\235\242\346\250\241\345\274\217", nullptr));
        label_display_2->setText(QApplication::translate("control_interface", "\345\217\214\347\224\273\351\235\242\346\250\241\345\274\217", nullptr));
        label_display_3->setText(QApplication::translate("control_interface", "\345\255\220\346\257\215\346\250\241\345\274\217", nullptr));
        label_versions_num->setText(QApplication::translate("control_interface", "v1.1.5", nullptr));
        label_host_led->setText(QString());
        label_1->setText(QApplication::translate("control_interface", "1", nullptr));
        label_2->setText(QApplication::translate("control_interface", "2", nullptr));
        label_3->setText(QApplication::translate("control_interface", "3", nullptr));
        browseReportBtn->setText(QString());
        zoomBtn->setText(QString());
        battery->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class control_interface: public Ui_control_interface {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONTROL_INTERFACE_H
